services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8080"
    environment:
      API_BASE: "http://api:8080"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
